 export const categoryWords = [
          "tee",
          "tees",
          "t-shirt",
          "tshirt",
          "shirt",
          "shirts",
          "pant",
          "pants",
          "jean",
          "jeans",
        ];

export const colorWords = [
          "black",
          "white",
          "blue",
          "red",
          "green",
          "yellow",
          "gray",
          "pink",
          "purple",
          "orange",
          "brown",
        ];

export const designWords = [
          "plain",
          "graphic",
          "distressed",
          "solid",
          "classic",
          "striped",
          "stripped",
        ];

export const styleWords = [
          "crew",
          "v-neck",
          "slim",
          "straight",
          "button",
          "casual",
          "skinny",
          "boot",
          "regular",
          "relaxed",
          "chino",
          "formal",
          "skinny",
        ];

export const orderKeywords = [
        "order",
        "shipping",
        "delivery",
        "track",
        "cancel",
        "return",
        "refund",
        "status",
        "tracking",
        "ship",
        "shipped",
        "transit",
        "out for delivery",
        "expected",
        "when will",
        "where is",
        "my order",
        "order status",
        "delivery date",
        "tracking number",
      ];

export const faqKeywords = [
        "size guide",
        "available sizes",
        "guide",
        "policy",
        "policies",
        "return policy",
        "shipping policy",
        "delivery policy",
        "refund",
        "exchange",
        "damaged",
        "support",
        "contact",
        "help",
        "faq",
        "question",
        "how to",
        "what is",
        "when can",
        "where can",
        "why",
        "how do",
        "do you",
        "can i",
        "is there",
        "are there",
        "what if",
        "how long",
        "how much",
        "cost",
        "charge",
        "free",
        "discount",
        "promo",
        "code",
        "gift",
        "invoice",
        "gst",
        "payment",
        "method",
        "cash",
        "cod",
        "upi",
        "card",
        "banking",
        "wallet",
        "all products",
        "you sell"
      ];

export const greetings = [
        "hi",
        "hii",
        "hello",
        "helloo",
        "hey",
        "heyyy",
        "how are you",
        "good morning",
        "good evening",
        "good afternoon",
      ];

export const CATEGORY_SYNONYMS = {
  tees: ["tee", "tees", "tshirt", "tshirts", "t-shirt", "t-shirts"],
  shirts: ["shirt", "shirts"],
  pants: ["pant", "pants", "trouser", "trousers", "chino", "chinos"],
  jeans: ["jean", "jeans", "denim"],
};

        // Check if user mentioned any material
export const materialWords = [
          "cotton",
          "denim",
          "polyester",
          "100% Cotton",
          "Cotton Blend",
          "Polyester Blend",
          "Denim",
        ];